name: CD

on:
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:
    inputs:
      aws-session-token:
        description: 'Session token'
        required: true
        default: 'NA'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        if: github.event.pull_request.merged
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ github.event.input.aws-session-token }}
          aws-region: us-east-1

      - name: Packer init
        run: packer init .

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.pkr.hcl

      # build artifact
      - name: Build Artifact
        run: packer build packer.pkr.hcl

      # additional steps to process artifacts
