name: CD

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'AWS session token'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Unset variables
        run: |
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN

      #TODO refresh credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ github.event.inputs.token }}
          aws-region: us-east-1

      - name: Packer init
        run: packer init .

      - name: Validate packer template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.pkr.hcl

      - name: Build artifact
        run: |
          packer build packer.pkr.hcl
          echo "ami_id=$(manifest.json | jq -r '.builds[-1].artifact_id' |  cut -d':' -f2)" >> $GITHUB_ENV
          echo ${{ env.ami_id }}

      - name: Terraform set AMI ID
        run: |
          echo "test"

      # TODO: Use ami output for terraform
      # TODO: SSH into instance and build app with IP and run
