# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    install:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [14.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
            mongodb-version: ['4.2']

        variables:
          APP_NODE_MODULE_DIRS: $(foreach dir, client server, $(subst %,$(dir),$(MKFILE_DIR)/app/%/node_modules))
          MKFILE_DIR: $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

        steps:
        - name: Git checkout
          uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            cache-dependency-path: app/server/package-lock.json
            #cache-dependency-path: app/client/package-lock.json

        - name: Start MongoDB ${{ matrix.mongodb-version }}
          uses: supercharge/mongodb-github-action@1.6.0
          with:
            mongodb-version: ${{ matrix.mongodb-version }}

        - name: Install npm
          run: npm install

        - name: Install dependencies
          run:  echo $(APP_NODE_MODULE_DIRS)
          #$(APP_NODE_MODULE_DIRS): cd $(@D) \ && npm install


      # TODO do not invoke make

    #- name: Make install
    #  run: make install

    #- name: Build application
    #  run: make build

    #- name: Test application
    #  run: make test

    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
