# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    install:
      name: Install dependencies
        runs-on: ubuntu-latest

        steps:
        - name: Git checkout
          uses: actions/checkout@v2

        - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
            cache: 'npm'
            #cache-dependency-path: app/server/package-lock.json
            #cache-dependency-path: app/client/package-lock.json

        - name: Start MongoDB '4.2'
          uses: supercharge/mongodb-github-action@1.6.0
          with:
            mongodb-version: '4.2'

        - name: Install client dependencies
          working-directory: ./app/client
          run: npm install

    build:
      name: Build server and client
      needs: install

      steps:
        - name: Build server
          run: |
            echo "Current directory"
            ls
            echo "Creating temp directory"
            mkdir temp
            echo "Copying server source to temp directory"
            cp -r ./app/server/src temp
            echo "Copying package files to temp directory"
            cp ./app/server/package* temp/
            echo "Installing server dependencies"
            cd temp
            npm install --prod --no-audit --no-fund
            rm -rf ./package*

        - name: Build client
          run: |
            cd ./app/client/scripts
            node build.js

      # TODO do not invoke make

    #- name: Make install
    #  run: make install

    #- name: Build application
    #  run: make build

    #- name: Test application
    #  run: make test

    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
